import { useState } from 'react';
import { v4 as uuid } from 'uuid'; // Importing uuid to generate unique ids for todos
import { Button, TextField } from "@mui/material";

function TodoForm({setNewtodo}) {
  const [addtodo, setAddtodo]=useState("") // Declaring state to store new todo item

  const handleAddTodo = () => {  // Function to handle adding a new todo
    const newTodoItem = { id: uuid(), task: addtodo, status:"incomplete", edit:false }; // Creating a new todo object with a unique id generated by uuid and the task entered by the user
    setNewtodo((prevNewTodo) => [...prevNewTodo, newTodoItem]); // Using the setNewtodo function passed down from parent component to update the list of todos with the new todo added to end of array.
    setAddtodo("") // Resetting the input field to empty string after adding the new todo
  };

  return (
    <div>
      <br></br>
      <TextField label="Enter Todo" color="secondary" focused value={addtodo} onChange={(e)=>setAddtodo(e.target.value)}/> {/* Input field for user to enter new todo task. The value of the input field is set to addtodo state and onChange event handler updates the addtodo state */}
      <br></br>
      <Button
        color="primary"
        disabled={false}  
        size="large"
        variant="filled"
        onClick={handleAddTodo} // Click event handler to trigger handleAddTodo function when Add Todo button is clicked
      >
        Add Todo
      </Button>
      <hr></hr> {/* Horizontal line separator */}
      <hr></hr> {/* Horizontal line separator */}
    </div>
  );
}

export default TodoForm; // Exporting TodoForm component as default